[build]
  publish = "public"  # HTML、CSSなどを配置する公開ディレクトリ
  functions = "functions"  # Netlify Functionsのコードを置くディレクトリ

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/upload"
  status = 200
